name: CI/CD for Angular App

on:
  push:
    branches:
      - OrderManagementAngular

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURECLIENTID }}
          client-secret: ${{ secrets.AZURECLIENTSECRET }}
          tenant-id: ${{ secrets.AZURETENANTID }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'OrderManagementCanApp'
          slot-name: 'production'
          publish-profile: ${{ secrets.ORDERPUBLISHPROFILE }}
          package: ./dist/*
